work_dir: work_dir/fsd_eval

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: data/train_joint.npy
  label_path: data/train_label.npy
  split: train
  debug: False
  random_choose: True
  random_shift: True
  random_move: True
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.3, 1]
  augmentation: 'avg'

test_feeder_args:
  data_path: data/test_A_joint.npy
  label_path: data/test_A_label.npy
  split: test
  window_size: 64
  p_interval: [0.95]
  debug: False

bone: False
motion: False

# processor
phase: test
save_score: False

# model
model: model.ctrgcn.Model
weights: work_dir/fsd_eval/runs-70-71890.pdparams
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.graph_17.Graph
  graph_args:
    labeling_mode: 'spatial'
  drop_out: 0.35

#optim
start_epoch: 0
weight_decay: 0.0012
base_lr: 0.1
lr_decay_rate: 0.1
step: [15, 35, 50, 60]
warm_up_epoch: 5

# training
cpu: False
device: []
batch_size: 32
test_batch_size: 32
num_epoch: 70
nesterov: True
